In [2]:
import pandas as pd
import numpy as np

# Series, Métodos e atributos

In [ ]:
# Obtendo todos os métodos que pode ser aplicado no Series
dir(pd.Series([1, 2, 3]))

In [6]:
# Atribuindo nome ao Series
ser = pd.Series([1, 2, 3, 4, 5], name='nome_serie')
ser

0    1
1    2
2    3
3    4
4    5
Name: nome_serie, dtype: int64

In [7]:
# Exibir o nome
ser.name

'nome_serie'

In [24]:
# Exibir os valores
ser.values

array([1, 2, 3, 4, 5], dtype=int64)

In [25]:
# Outra maneira de receber os valores(Um ndarray NumPy que representa os valores nesta série ou índice)
ser.to_numpy()

array([1, 2, 3, 4, 5], dtype=int64)

In [22]:
# Exibir os indices
ser.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [23]:
# Transformar indices em uma lista
ser.index.to_list()

['a', 'b', 'c', 'd', 'e']

In [57]:
# Substituir indices
ser.index = ['a', 'b', 'c', 'd', 'e']
ser

a    1
b    2
c    3
d    4
e    5
Name: nome_serie, dtype: int64

In [65]:
# Renomeando indices (O inplace=True serve para que ele altere Serie)
ser.rename({'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}, inplace=True)
ser

1    1
2    2
3    3
4    4
5    5
Name: nome_serie, dtype: int64

In [66]:
# Indexação puramente baseada em localização inteira para seleção por posição.
ser.iloc[0]

1

In [67]:
# Pode ser usado mais de um index e retornar utilizando o .to_numpy() para obter um array com o resultado
ser.iloc[[0, 2]].to_numpy()

array([1, 3], dtype=int64)

In [10]:
# Gerar dados
frutas = ['Banana', 'Maça', 'Uva', 'Laranja', 'Goiaba', np.nan]
ser = pd.Series(np.random.choice(frutas) for item in range(200))
ser

0       Goiaba
1          Uva
2       Goiaba
3       Goiaba
4       Goiaba
        ...   
195    Laranja
196        nan
197     Banana
198    Laranja
199     Banana
Length: 200, dtype: object

In [11]:
# Exibir a quantidade de itens dentro do Series
ser.count()

200

In [13]:
# Retorne uma série contendo contagens de valores únicos.
ser.value_counts()

Goiaba     39
Maça       34
Uva        34
Laranja    34
Banana     31
nan        28
dtype: int64

In [19]:
# Exibe os valores unicos
ser.unique()

array(['Goiaba', 'Uva', 'Maça', 'nan', 'Banana', 'Laranja'], dtype=object)

In [22]:
# Exibe em números a quantidade de valores unicos
ser.nunique()

6